### ISSUE TITLE
CSS Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v5#1]
In CC5215, /setup/styles/style.css, line 138:
`font-size: 1.25rem;`
I think `rem` is not valid.

**Comment by abrookbanks** [comment]
Changed to "em". Thanks!

**Comment by bhsmither** [comment]
http://caniuse.com/rem

I was not aware of this.

You may want to change it back.

**Comment by abrookbanks** [comment]
I thought it was only relevant if the root element was specifically "rem" defined.. Maybe not. I'm not sure it actually makes a difference in our case either way.
