### ISSUE TITLE
Problem with multiple items discount

### ISSUE THREAD

**Issue by brulaap** [cubecart/v5#20]
I have a problem showing the multiple items discount on the product page.
all is set normally on the admin section but it shows up wrong on the page.
strange is that when i do a test order it comes perfect on the invoice. All data seems to be send correctly to the product page but somehow it ends up totally wrong.

I have set up the page for 5pcs, 10pcs and 25pcs nd before it all showed the same low value of a couple of euro while it had to be around 1400 euro. check if i did put a . instead of a , but all seems fine. anyway it ends up on the invoice perfect..

Stranger is that this morning different values showed up ( a little higher value)...
im lost...
![error1](https://cloud.githubusercontent.com/assets/12066510/7273268/4e1eed52-e8f2-11e4-9ea8-c869e9dfe4a4.jpg)
![error2](https://cloud.githubusercontent.com/assets/12066510/7273271/51f6d26e-e8f2-11e4-9a74-32fa6b2bce27.jpg)

it worked perfect before.. no upgrades done. working on v5.2.14
i just noticed this after a while by accident...

prices mentioned in admin section are excluding VAT by a module i use from Noodlemans.
which also worked normally before.

**Comment by brulaap** [comment]
after some working with this problem i found out that prices under 1000 like 999.99 work fine. then over that amount the product page seems to loose 2 digits... now idea how that can be fixed.. keeping in mind im not a grammer... any idea's?

**Comment by abrookbanks** [comment]
I'm sorry but this is unreproducible on a default install. Please test our CC5 demo store. Please send a support ticket if you need us to take a look. 

https://demo.cubecart.com/cc5/admin 
User: admin 
Pass: password

![screen shot 2015-04-24 at 08 22 45](https://cloud.githubusercontent.com/assets/4520803/7314322/60350a7a-ea5b-11e4-874f-cb6187736cf0.png)
![screen shot 2015-04-24 at 08 23 06](https://cloud.githubusercontent.com/assets/4520803/7314323/60512ed0-ea5b-11e4-884f-aa2b65eeaba9.png)

**Comment by brulaap** [comment]
Its solved. Was something in the module from Alec…

Its correct again but all currencies over 999,99 did that..
only it shows 1,120.50 euro.. instead 1.125,50 were the . and , is correct placed…
Alec says it might be solved with CC6.. is this related to CC5?

 

 

  

With kind regards,


L. Mölenberg

Shop:   <http://shop.righthere.nu/> http://shop.righthere.nu
Email:  <mailto:newtech@righthere.nu> newtech@righthere.nu
Web:   <http://www.righthere.nu/> http://www.righthere.nu


P Please consider the environment before printing this e-mail and save some trees!

******************************************************************************************

Notice to recipient: this e-mail is meant for only the intended recipient of the transmission, and may be a communication privileged by law, subject to  export control restrictions  or that otherwise contains proprietary and confidential information. If you received this e-mail by mistake, please notify us immediately by replying to this message and then destroy it and do not review, disclose, copy or distribute it.  Thank you in advance for your cooperation.

*******************************************************************************
