### ISSUE TITLE
cookie problems with admin log in v5.2.14

### ISSUE THREAD

**Issue by radikls** [cubecart/v5#5]
Hi there,

I'm having a problem logging into the admin control panel, which was originally hightlighted by our client but I've now been able to replicate on my PC.

I'm using Firefox but also replicates in Safari, Chrome, IE8 (this is an XP machine)

I found that if I run the first part of the 'set up' it creates a cookie, and so long as this cookie exists then I can log in - if I delete this cookie I can't login (no error messages) - this is for all browsers

COOKIE CONTENTS:

Name: PHPSESSID
Content: 5d3bshsftfh4m7c072mepprf80
Host: www.trailer-parts-uk.com
Path: /
SendFor: Any type of connection
Expires: At end of session

The first part of the setup shows:

Compatibility Check
5.2.17 PHP 5.2.3+
5.5.36 MySQL 4.1+
Installed GD Image Library
Installed cURL
Installed IonCube PHP Loader

I've run 'repair ' on the admin and sessions tables and CubeCart_blocker table is empty.

**Comment by abrookbanks** [comment]
Thanks for this. I believe this is a configuration issue of some kind. If you can raise a tech support ticket we can investigate further. I quite confident this isn't a bug but if it is this issue will be updated accordingly.
